name: Storybook Publish
run-name: ${{ github.actor }}의 스토리북 배포
on: workflow_dispatch

jobs:
 storybook:
  runs-on: ubuntu-latest
  outputs:
   status: ${{ job.status }}
  steps:
   - name: checkout repository
     uses: actions/checkout@v3
     with:
      fetch-depth: 0
      
   - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

   - name: cache dependencies
     id: cache
     uses: actions/cache@v3
     with:
      path: '**/node_modules'
      key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-storybook

   - name: depedency install
     if: steps.cache.outputs.cache-hit != 'true'
     run: pnpm install

   - name: storybook build
     run: pnpm run build-storybook

   - name: publish to gh-pages branch
     uses: peaceiris/actions-gh-pages@v3
     with:
      github_token: ${{ secrets.GH_ACTIONS_TOKEN }}
      publish_dir: ./storybook-static
